/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author arthur
 */
public class tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form tela_principal
     */
    public tela_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_cad_cliente = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_cad_licenca = new javax.swing.JButton();
        btn_licenças = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel8);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Nome do Sistema");
        getContentPane().add(jLabel12);

        btn_cad_cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cad_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Client.png"))); // NOI18N
        btn_cad_cliente.setText("Cadastrar Cliente");
        btn_cad_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cad_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cad_cliente);

        btn_clientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clients-icon.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clientes);

        btn_cad_licenca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_cad_licenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/License-manager-icon (1).png"))); // NOI18N
        btn_cad_licenca.setText("Cadastrar Licença");
        btn_cad_licenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cad_licencaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cad_licenca);

        btn_licenças.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_licenças.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/License-manager-icon.png"))); // NOI18N
        btn_licenças.setText("Licenças");
        getContentPane().add(btn_licenças);

        btn_sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Actions-window-close-icon.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sair);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        tela_principal btn_sair = new tela_principal();
        dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cad_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_clienteActionPerformed
        // TODO add your handling code here:
        tela_cad_cliente btn_cad_cliente = new tela_cad_cliente();
        btn_cad_cliente.setVisible(true);
    }//GEN-LAST:event_btn_cad_clienteActionPerformed

    private void btn_cad_licencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cad_licencaActionPerformed
        // TODO add your handling code here:
        tela_cad_licencas btn_cad_licenca = new tela_cad_licencas();
        btn_cad_licenca.setVisible(true);
    }//GEN-LAST:event_btn_cad_licencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cad_cliente;
    private javax.swing.JButton btn_cad_licenca;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_licenças;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
